name: 'Auto Request Review'
description: 'Automatically requests review of a pull request based on files changes and/or groups the author belongs to 🤖'
branding:
  icon: 'at-sign'
  color: 'green'
inputs:
  token:
    required: true
  config:
    required: false
    default: '.github/auto_request_review.yml'
  use_local:
    required: false
    default: 'false'
  number_of_reviewers:
    description: 'The number of reviewers to add'
    required: false
    default: '1'
  number_of_assignees:
    description: 'The number of assignees to add'
    required: false
    default: '1'
  ignored_reviewers:
    description: 'A comma separated list of reviewers to NOT add as reviewers'
    required: false
    default: ''
outputs:
  requested_reviewers:
    description: 'A comma seperated list of github usernames'
  assigned_reviewers:
    description: 'A comma separated list of github usernames'
runs:
  using: 'node16'
  main: 'dist/index.js'
